name: exam_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  collection: ^1.16.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
